version: '3.8'

services:
  client:
    build:
      context: ./client
    ports:
      - "5633:80" # Map host port 5633 to container port 80 (Nginx)
    restart: always
    depends_on:
      - server

  server:
    build:
      context: ./server
    ports:
      - "5632:8080" # Map host port 5632 to container port 8080 (Node.js)
    environment:
      # ---- Centralized Configuration ----
      # Replace placeholder values before running 'docker-compose up'
      - NODE_ENV=production
      - PORT=8080
      - OPENAI_API_BASE_URL=https://api.openai.com/v1
      - OPENAI_API_KEY="your_api_key_here" # IMPORTANT: Replace with your actual OpenAI API Key
      - ADMIN_API_KEY="a_very_secret_key_for_admin_operations" # IMPORTANT: Replace with your desired admin password
    volumes:
      - ./server/database:/app/database # Persist SQLite database to the host filesystem
    restart: always
